apiVersion: v1
kind: Template
metadata:
  name: starter-arbitrary-uid
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: starter-arbitrary-uid
    name: starter-arbitrary-uid
  spec:
    replicas: 1
    selector:
      app: starter-arbitrary-uid
      deploymentconfig: starter-arbitrary-uid
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: starter-arbitrary-uid
          deploymentconfig: starter-arbitrary-uid
      spec:
        containers:
        - image: starter-arbitrary-uid
          imagePullPolicy: Always
          name: starter-arbitrary-uid
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - starter-arbitrary-uid
        from:
          kind: ImageStreamTag
          name: starter-arbitrary-uid:latest
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: starter-arbitrary-uid
    name: starter-arbitrary-uid
  spec:
    tags:
    - name: "starter-arbitrary-uid"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "starter-arbitrary-uid"
  spec:
    source:
      git:
        uri: https://github.com/RHsyseng/container-rhel-examples
      contextDir: "starter-arbitrary-uid"
    strategy: 
      type: "Docker"
    output:
      to:
        kind: "ImageStreamTag"
        name: "starter-arbitrary-uid:latest"
    triggers:
    - type: ConfigChange